### ISSUE TITLE
Support container.args and container.command

### ISSUE THREAD

**Issue by gonewaje** [deployaja/deployaja-cli#12]
### 🚀 Feature Request  
Support container.args and container.command in `deployaja.yaml`
---

#### ✅ Current Behavior

1. **Single Port Limitation**  
`deployaja.yaml` only supports container.image and container.port field:
```yaml
container:
  image: nginx:latest
  port: 80
```

💡 Desired Behavior
Should be support for args and command where is sometimes build in image needs custom args/command
Allow defining args and command in deployaja.yaml, such as:

```yaml
container:
  image: nginx:latest
  ports: 80
  command: ["my", "container", "command"]
  args: ["my", "args"]
```

🙋‍♂️ Who Will Benefit from This?
- All CLI users using aja deploy
- Teams deploying apps with custom args and command

Suggested Labels:
enhancement, cli, feature, yaml-support
