### ISSUE TITLE
Support attach config files (yaml, conf, env, json)

### ISSUE THREAD

**Issue by gonewaje** [deployaja/deployaja-cli#13]
### 🚀 Feature Request  
Support attach or directly write config files in `deployaja.yaml`
---

#### ✅ Current Behavior

1. **only attach volumes**  
`deployaja.yaml` only supports attaching volume field:
```yaml
volumes:
    - name: my-data
      size: 1Gi
      mountPath: /my/data
```

💡 Desired Behavior
Should be support configmap or attach config files or write it directly in deployaja.yaml

```yaml
env:
      - name: MY_CONFIG_LOCATION
         value: "file:/config/custom.yaml"        -> refer to local config



volumes:
  - name: my-config
    type: config
    path: ./custom.yaml         # Local path to your config file
    mountPath: /config/custom.yaml
    subPath: custom.yaml
```

🙋‍♂️ Who Will Benefit from This?
- All CLI users using aja deploy
- Teams deploying apps with custom configuration

Suggested Labels:
enhancement, cli, feature, yaml-support
