### ISSUE TITLE
Support multiple container.port in deployaja.yaml

### ISSUE THREAD

**Issue by gonewaje** [deployaja/deployaja-cli#8]
### 🚀 Feature Request  
Support multiple container ports in `deployaja.yaml`
---

#### ✅ Current Behavior

1. **Single Port Limitation**  
`deployaja.yaml` only supports a single `container.port` field:
```yaml
container:
  image: nginx:latest
  port: 80
```

💡 Desired Behavior
Multiple Ports Support
Allow defining multiple ports in deployaja.yaml, such as:

```yaml
container:
  image: nginx:latest
  ports:
    - 8000
    - 8001
    - 8002
```

🙋‍♂️ Who Will Benefit from This?
- All CLI users using aja deploy
- Teams deploying apps with multiple exposed ports (e.g., HTTP + gRPC or admin/metrics endpoints)

Suggested Labels:
enhancement, cli, feature, yaml-support
